server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: admin19-sk-order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**,/orderStates/**
        - id: admin19-sk-delivery2
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**
        - id: admin19-sk-check
          uri: http://localhost:8083
          predicates:
            - Path=/checks/**
        - id: admin19-sk-product
          uri: http://localhost:8084
          predicates:
            - Path=/products/**
        - id: admin19-sk-payment
          uri: http://localhost:8085
          predicates:
            - Path=/payments/**
        - id: admin19-sk-notify1
          uri: http://localhost:8086
          predicates:
            - Path=
        - id: admin19-sk-satisfaction
          uri: http://localhost:8087
          predicates:
            - Path=/satisfactions/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://admin19-sk-order:8080
          predicates:
            - Path=/orders/**,/orderStates/**
        - id: Delivery
          uri: http://admin19-sk-delivery2:8080
          predicates:
            - Path=/deliveries/**
        - id: Check
          uri: http://admin19-sk-check:8080
          predicates:
            - Path=/checks/**
        - id: Product
          uri: http://admin19-sk-product:8080
          predicates:
            - Path=/products/**
        - id: Payment
          uri: http://admin19-sk-payment:8080
          predicates:
            - Path=/payments/**
        - id: Notify
          uri: http://admin19-sk-notify1:8080
          predicates:
            - Path=
        - id: Satisfaction
          uri: http://admin19-sk-satisfaction:8080
          predicates:
            - Path=/satisfactions/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
